import pandas as pd
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
import joblib
import os

def train():
    print("Starting AI Model Training...")
    
    # Path to the CSV file generated by Claude AI
    csv_path = os.path.join(os.path.dirname(__file__), 'engine_synthetic_training_data.csv')
    
    if not os.path.exists(csv_path):
        print(f"Error: Could not find {csv_path}. Please make sure the CSV is named correctly.")
        return
        
    df = pd.read_csv(csv_path)
    
    # Strip whitespace from column names just in case
    df.columns = df.columns.str.strip()
    
    # 1. Features (Inputs)
    # Make sure the columns match the CSV exactly
    features = ['rpm', 'coolant_temp', 'engine_load', 'fuel_rate', 'idle_time']
    X = df[features]
    
    # 2. Targets (Outputs)
    y_event = df['event_type']
    y_multi = df['severity_multi']
    y_wear = df['wear_units']
    
    print("Training Event Type Classifier...")
    # Classifier for predicting the event type (string)
    clf_event = RandomForestClassifier(n_estimators=50, max_depth=10, random_state=42)
    clf_event.fit(X, y_event)
    
    print("Training Severity Multiplier Regressor...")
    # Regressor for predicting the continuous severity multiplier
    reg_multi = RandomForestRegressor(n_estimators=50, max_depth=10, random_state=42)
    reg_multi.fit(X, y_multi)
    
    print("Training Wear Units Regressor...")
    # Regressor for predicting the continuous wear units
    reg_wear = RandomForestRegressor(n_estimators=50, max_depth=10, random_state=42)
    reg_wear.fit(X, y_wear)
    
    # Bundle the models together into a dictionary
    models = {
        'event_classifier': clf_event,
        'multi_regressor': reg_multi,
        'wear_regressor': reg_wear
    }
    
    # Save the bundled models to a .pkl file
    model_path = os.path.join(os.path.dirname(__file__), 'models', 'engine_wear_model.pkl')
    joblib.dump(models, model_path)
    
    print(f"Success! Model trained and saved to {model_path}")

if __name__ == "__main__":
    train()
